/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICBToken } from "./ICBToken";
export type { TokenReceiver } from "./TokenReceiver";
export type { TokenSender } from "./TokenSender";
